package monedas;

/**
 *
 * @author User
 */
public class Funcion extends javax.swing.JFrame {

    /**
     * Creates new form Funcion
     */
    public Funcion() {
        initComponents();
        this.setTitle("Convercion De Monedas");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtMon = new javax.swing.JTextField();
        TxtCam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Moneda");

        jLabel2.setText("Cambio");

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lps", "Rublo Ruso", "Dolar", "Euro", "Franco Suizo" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lps", "Rublo Ruso", "Dolar", "Euro", "Franco Suizo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtMon)
                                    .addComponent(TxtCam, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TxtCam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double mon;
        mon=Double.parseDouble(this.TxtMon.getText());
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.TxtCam.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 1){
            this.TxtCam.setText(Double.parseDouble(mon+"")*2.64+"");
        }else if(jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 2){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*0.0408));
        }else if(jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 3){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*0.0361));
        }else if(jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 4){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*0.0405));
        }
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.TxtCam.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 0){
            this.TxtCam.setText(""+Double.parseDouble(mon+"")*0.38);
        }else if(jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 2){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*0.0155));
        }else if(jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 3){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*0.0137));
        }else if(jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 4){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*0.0154));
        }
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.TxtCam.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 2 && jComboBox2.getSelectedIndex() == 0){
            this.TxtCam.setText(Double.parseDouble(mon+"")*24.52+"");
        }else if(jComboBox1.getSelectedIndex() == 2 && jComboBox2.getSelectedIndex() == 1){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*64.65));
        }else if(jComboBox1.getSelectedIndex() == 2 && jComboBox2.getSelectedIndex() == 3){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*0.88));
        }else if(jComboBox1.getSelectedIndex() == 2 && jComboBox2.getSelectedIndex() == 4){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*0.99));
        }
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.TxtCam.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 3 && jComboBox2.getSelectedIndex() == 0){
            this.TxtCam.setText(Double.parseDouble(mon+"")*27.72+"");
        }else if(jComboBox1.getSelectedIndex() == 3 && jComboBox2.getSelectedIndex() == 1){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")* 73.10));
        }else if(jComboBox1.getSelectedIndex() == 3 && jComboBox2.getSelectedIndex() == 2){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*1.13));
        }else if(jComboBox1.getSelectedIndex() == 3 && jComboBox2.getSelectedIndex() == 4){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")* 1.12));
        }
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.TxtCam.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 4 && jComboBox2.getSelectedIndex() == 0){
            this.TxtCam.setText(Double.parseDouble(mon+"")*24.69+"");
        }else if(jComboBox1.getSelectedIndex() == 4 && jComboBox2.getSelectedIndex() == 1){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*65.09));
        }else if(jComboBox1.getSelectedIndex() == 4 && jComboBox2.getSelectedIndex() == 2){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")*1.01));
        }else if(jComboBox1.getSelectedIndex() == 4 && jComboBox2.getSelectedIndex() == 3){
            this.TxtCam.setText(""+(Double.parseDouble(mon+"")* 0.89));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCam;
    private javax.swing.JTextField TxtMon;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
